config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :games, only: %i[index show new create], param: :code
  resources :users, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :votes
  has_many :users, through: :votes

  enum status: { not_started: 'not_started', voting: 'voting', voting_ended: 'voting_ended' }

  STATUS_CHANGE_MAP = {
    'not_started' => 'voting',
    'voting' => 'voting_ended',
    'voting_ended' => 'voting'
  }.freeze

  validates :name, presence: true
  validate :validate_status_change, if: -> { status_changed? }

  before_create :set_code

  private

  def set_code
    self.code = code.presence || generate_code
  end

  def generate_code
    loop do
      random_code = SecureRandom.hex(10)
      break random_code unless Game.where(code: random_code).exists?
    end
  end

  def validate_status_change
    valid_status = STATUS_CHANGE_MAP[status_was]
    return if status == valid_status

    errors.add(:base, 'invalid game status change')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :votes
  has_many :games, through: :votes

  validates :name, presence: true
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound do
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  if Rails.env.production?
    rescue_from StandardError do |e|
      Rollbar.error(e)
      render file: "#{Rails.root}/public/500.html", layout: false, status: :internal_server_error
    end
  end

  def current_user
    return @current_user if @current_user_loaded

    @current_user = (User.find_by(id: session[:current_user_id]) if session[:current_user_id])
    @current_user_loaded = true

    @current_user
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :redirect_unless_current_suer, only: %i[new create]
  before_action :set_game, only: %i[edit update destroy]
  before_action :set_game_by_code, only: %i[show]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/:code
  def show
    session[:game_code] = @game.code
    return redirect_to new_user_url unless current_user

    event = {
      type: 'user_join',
      params: {
        game: { id: @game.id },
        user: { id: current_user.id }
      }
    }
    PokerGameService.new(event).run

    @user_data = current_user.to_json
    @game_data = GameSerializer.new(@game).run.to_json
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      session[:game_code] = @game.code
      redirect_to game_url(@game.code), notice: 'Game was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def redirect_unless_current_suer
    redirect_to new_user_url unless current_user
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def set_game_by_code
    @game = Game.find_by!(code: params[:code])
  end

  def game_params
    params.require(:game).permit(:name, :code)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    return redirect_to new_game_path if current_user

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id

      if session[:game_code] && (game = Game.find_by(code: session[:game_code]))
        game.votes.create(user: @user)
        redirect_to game_url(game.code)
      else
        redirect_to new_game_url
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to new_game_url
    else
      redirect_to new_user_url
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Game Name*' %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, placeholder: 'custom code' %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn-border-pink" %>
  </div>
<% end %>

app/views/games/index.html.erb
<div class="container mx-auto">
  <div>
    <h1>Games</h1>
    <hr>
    <%= link_to 'Add a new game', new_game_path %>
    <p id="notice"><%= notice %></p>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>URL</th>
      </tr>
    </thead>
    <% @games.each do |game| %>
    <tbody>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to(game_url(game.code), game_url(game.code)) %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/games/new.html.erb
<div class="container mx-auto">
  <img
    src="https://images.unsplash.com/photo-1598100223749-1df46ef2ddac?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1335&q=80&auto=format&fit=crop&w=634&q=80"
    alt="image">
  <div class="container-text">
    <h1>New Game</h1>
    <p>Start here and sharp the conversation</p>
    <%= render 'form', game: @game %>
    <%= link_to 'All Game Lists', games_path %>
    <span>© 2021 darren987469 All Rights Reserved</span>
  </div>
</div>

app/views/games/show.html.erb
<div class="container mx-auto">
  <div>
    <h3><%= @game.name %></h3>
    <hr>
    <strong>Code:</strong>
    <%= @game.code %>

    <p id="notice"><%= notice %></p>
    <strong>Invite people:</strong>
    <%= link_to(game_url(@game.code), game_url(@game.code)) %>
    <p class="mt-5"><%= link_to 'New game?', new_game_path %></p>
    <p><%= link_to 'All Game Lists', games_path %></p>
  </div>

  <%= javascript_pack_tag 'games/main', 'data-turbolinks-track': 'reload' %>
  <div id="gameApp" data-user="<%= @user_data %>" data-game="<%= @game_data %>">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanningPoker</title>
     <%= favicon_link_tag asset_path('icon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(user.errors.count, "error") %> prohibited this game from being saved:</p>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Your Name' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn-border-pink" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container mx-auto">
  <img
    src="https://images.unsplash.com/photo-1598100223749-1df46ef2ddac?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1335&q=80&auto=format&fit=crop&w=634&q=80"
    alt="image">
  <div class="container-text">
    <h1>Planning Poker</h1>
    <p>Start here and sharp the conversation</p>
    <%= render 'form', user: @user %>
    <span>© 2021 darren987469 All Rights Reserved</span>
  </div>
</div>